version: "3.5"
services:
  kafka-sender:
    image: kafka-sender
    container_name: kafka-sender
    ports:
      - "${PORT}:${PORT}"
    build:
      context: ${GOPATH}/src/github.com/dwarvesf/kafka-sender
    env_file:
      - .env
    external_links:
      - consul:consul-server
      - service_mesh_db
    networks:
      service-mesh:
        ipv4_address: 10.5.0.150

networks:
  service-mesh:
    name: service-mesh-nw
